In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#Activity_QUIZ

In [ ]:
#Load dataset
df = pd.read_csv('employee_data.csv')
print("Emplyee Data :\n", df.head())

Emplyee Data :
    ID Gender  Experience (Years)               Position  Salary
0   1      F                   4        DevOps Engineer  109976
1   2      M                   6        DevOps Engineer  120088
2   3      M                  17          Web Developer  181301
3   4      M                   7  Systems Administrator   77530
4   5      F                  13  Systems Administrator  152397

In [ ]:
print(df.columns)

Index(['ID', 'Gender', 'Experience (Years)', 'Position', 'Salary'], dtype='object')

In [ ]:
#Explore data
print ("Missing values in each column:\n", df.isnull().sum())

Missing values in each column:
 ID                    0
Gender                0
Experience (Years)    0
Position              0
Salary                0
dtype: int64

In [ ]:
#Filter data
filtered_df = df[df['Experience (Years)']>10]
print("Rows where experience is greater than 10 years:\n",filtered_df)

Rows where experience is greater than 10 years:
       ID Gender  Experience (Years)                      Position  Salary
2      3      M                  17                 Web Developer  181301
4      5      F                  13         Systems Administrator  152397
5      6      F                  13                 Web Developer  114998
6      7      F                  11         Systems Administrator   82328
10    11      F                  19         Network Administrator  158856
..   ...    ...                 ...                           ...     ...
390  391      M                  11         IT Support Specialist   66076
395  396      F                  19     Cloud Solutions Architect  236045
396  397      F                  20                 Web Developer  182770
398  399      M                  18  Database Administrator (DBA)  129996
399  400      F                  11           IT Security Analyst  169058

[185 rows x 5 columns]

In [ ]:
#Filter data
filtered_df = df[df['Experience (Years)']<10]
print("Rows where experience is less than 10 years:\n",filtered_df)

Rows where experience is less than 10 years:
       ID Gender  Experience (Years)                   Position  Salary
0      1      F                   4            DevOps Engineer  109976
1      2      M                   6            DevOps Engineer  120088
3      4      M                   7      Systems Administrator   77530
7      8      M                   2            DevOps Engineer  111494
8      9      F                   6            DevOps Engineer  105563
..   ...    ...                 ...                        ...     ...
391  392      F                   3  Cloud Solutions Architect  159870
392  393      F                   1      Network Administrator   79333
393  394      M                   2          Software Engineer   91029
394  395      M                   3      IT Support Specialist   54938
397  398      F                   9      Network Administrator   85550

[193 rows x 5 columns]

In [ ]:
#Group Data
df.groupby(by = "Gender")

In [80]:
byGender = df.groupby(by = "Gender")

In [85]:
df.Gender

0      F
1      M
2      M
3      M
4      F
      ..
395    F
396    F
397    F
398    M
399    F
Name: Gender, Length: 400, dtype: object

In [79]:
#Group Data
df.groupby(by = "Position")

In [ ]:
byPosition = df.groupby(by = "Position")

In [86]:
df.Position

0                   DevOps Engineer
1                   DevOps Engineer
2                     Web Developer
3             Systems Administrator
4             Systems Administrator
                   ...
395       Cloud Solutions Architect
396                   Web Developer
397           Network Administrator
398    Database Administrator (DBA)
399             IT Security Analyst
Name: Position, Length: 400, dtype: object

In [ ]:
#Laboratory Quiz

In [ ]:
#Generate Data
d = {'Branches': ['Store 1', 'Store 1','Store 2', 'Store 2', 'Store 3','Store 3','Store 4', 'Store 4', 'Store 5', 'Store 5', 'Store 5'],
     'Employee': ['Vanessa', 'Alexa','James', 'Charlie', 'Billie','Sam','Eckert','John','Millie','Jonas','Xander'],
     'Sales': [300, 175, 250, 120, 400, 500, 300, 200, 600, 300, 400]
}

In [ ]:
ds = pd.DataFrame(d)

In [ ]:
ds

   Branches Employee  Sales
0   Store 1  Vanessa    300
1   Store 1    Alexa    175
2   Store 2    James    250
3   Store 2  Charlie    120
4   Store 3   Billie    400
5   Store 3      Sam    500
6   Store 4   Eckert    300
7   Store 4     John    200
8   Store 5   Millie    600
9   Store 5    Jonas    300
10  Store 5   Xander    400

In [ ]:
#Explore data
print ("Missing values in each column:\n", ds.isnull().sum())

Missing values in each column:
 Branches    0
Employee    0
Sales       0
dtype: int64

In [ ]:
#Filter Data
filtered_ds = ds[ds['Sales']<300]
print("Rows where experience is less than 300:\n",filtered_ds)

Rows where experience is less than 300:
   Branches Employee  Sales
1  Store 1    Alexa    175
2  Store 2    James    250
3  Store 2  Charlie    120
7  Store 4     John    200

In [ ]:
filtered_ds = ds[ds['Sales']>300]
print("Rows where experience is greater than 300:\n",filtered_ds)

Rows where experience is greater than 300:
    Branches Employee  Sales
4   Store 3   Billie    400
5   Store 3      Sam    500
8   Store 5   Millie    600
10  Store 5   Xander    400

In [ ]:
# Group together by Column Name

ds.groupby(by = "Branches")

In [ ]:
byBranch = ds.groupby(by = "Branches")

In [ ]:
byBranch

In [ ]:
byBranch.sum()

                   Employee  Sales
Branches
Store 1        VanessaAlexa    475
Store 2        JamesCharlie    370
Store 3           BillieSam    900
Store 4          EckertJohn    500
Store 5   MillieJonasXander   1300