In [139]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import requests
from bs4 import BeautifulSoup
warnings.filterwarnings('ignore')

Web Scrape NBA Standings from CBS Sports

In [140]:
#URL
url = 'https://www.cbssports.com/nba/standings/'

#Send Request
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36'}


# Response

response = requests.get(url = url, headers = headers)

#Create a bs4 object to parse the html content
nbaTbls = BeautifulSoup(response.content, 'html.parser')

Eastern Conference

In [141]:
#Find the tbody containing east conference teams, you can use select ('tbody')[0],means first tbody found
eastConf = nbaTbls.select('tbody')[0]

In [142]:
# Find the table containing teams
#table_teams = eastConf.select_one('col.TableBase-colGroupCol--team tbody')
# Find the table with the stats
#table_data = eastConf.select_one('colgroup.TableBase-colGroup')
#table_data
#table_teams

In [143]:
#Find all Team Names, you can use the .get_text().strip to get the text and strip extra spaces

team = []

for teams in eastConf.find_all('span', class_ = 'TeamName'):

  team.append(teams.get_text())

#team

In [144]:
#Data  for Eastern Conference Teams

data = []
for tr in eastConf.find_all('tr'):
  row_data = []
  for i, td in enumerate(tr.find_all('td')):
    if i > 1:
      row_data.append(td.get_text().strip())
  data.append(row_data)

#data

In [145]:
#Construct Data Frame of Eastern Coference Teams

team_df = pd.DataFrame(team, columns = ['Team'])
team_df

            Team
0      Cleveland
1         Boston
2       New York
3      Milwaukee
4        Indiana
5        Detroit
6        Atlanta
7        Orlando
8          Miami
9        Chicago
10       Toronto
11      Brooklyn
12  Philadelphia
13     Charlotte
14    Washington

In [146]:
#Column Names

col_names = ['W','L','PCT','GB','PPG','OPPG','Diff','Home','Road','Div','Conf','STRK','L10','W','Div','Post']
#col_names
print(len(data[0]))

16

In [147]:
#Construct Data Frame for Eastern Conference Teams

team_data = pd.DataFrame(data, columns = col_names)
team_data

,W,L,PCT,GB,PPG,OPPG,Diff,Home,Road,Div,Conf,STRK,L10,W,Div,Post
0,55,10,.846,—,122.7,111.4,11.3,30-4,25-6,11-1,38-7,W15,10-0,62.9,100.0%,100.0%
1,47,19,.712,8.5,116.8,108.3,8.5,23-12,24-7,11-2,32-11,L1,7-3,59.7,98.5%,100.0%
2,42,23,.646,13.0,117.1,112.7,4.4,21-11,21-12,10-3,28-13,W2,5-5,52.2,1.5%,100.0%
3,36,28,.563,18.5,114.6,112.5,2.1,22-11,14-17,6-7,26-19,L3,6-4,43.9,0.0%,88.5%
4,36,28,.563,18.5,116.4,115.4,1.0,20-10,16-18,8-5,21-20,W1,5-5,46.0,0.0%,98.0%
5,37,29,.561,18.5,114.8,112.9,1.9,18-14,19-15,4-9,25-20,W2,7-3,42.8,0.0%,88.6%
6,32,34,.485,23.5,117.4,119.6,-2.2,17-16,15-18,8-4,24-18,W4,6-4,39.0,45.7%,73.4%
7,30,36,.455,25.5,104.3,106.1,-1.8,18-16,12-20,8-3,24-20,L1,3-7,38.2,24.5%,60.9%
8,29,36,.446,26.0,109.9,110.6,-0.7,15-16,14-20,7-5,18-22,L5,3-7,38.5,29.8%,60.6%
9,27,38,.415,28.0,116.6,120.3,-3.7,12-22,15-16,4-11,22-23,W3,5-5,31.7,0.0%,3.1%
10,23,43,.348,32.5,110.8,115.7,-4.9,16-20,7-23,5-8,15-29,W2,6-4,28.2,0.0%,<1.0%
11,22,43,.338,33.0,105.2,111.5,-6.3,10-21,12-22,3-8,12-28,L1,2-8,31.0,0.0%,2.4%
12,22,43,.338,33.0,109.4,114.4,-5.0,12-21,10-22,3-11,14-27,L2,2-8,33.9,0.0%,23.6%
13,16,49,.246,39.0,105.4,113.0,-7.6,10-24,6-25,1-12,9-33,L1,2-8,24.1,0.0%,<1.0%
14,13,51,.203,41.5,108.3,120.6,-12.3,7-26,6-25,6-6,10-28,L2,4-6,15.6,0.0%,0.0%

In [148]:
#Combine both DataFrame (Eastern Conference)

df_final = pd.concat([team_df, team_data], axis = 1)
df_final

,Team,W,L,PCT,GB,PPG,OPPG,Diff,Home,Road,Div,Conf,STRK,L10,W,Div,Post
0,Cleveland,55,10,.846,—,122.7,111.4,11.3,30-4,25-6,11-1,38-7,W15,10-0,62.9,100.0%,100.0%
1,Boston,47,19,.712,8.5,116.8,108.3,8.5,23-12,24-7,11-2,32-11,L1,7-3,59.7,98.5%,100.0%
2,New York,42,23,.646,13.0,117.1,112.7,4.4,21-11,21-12,10-3,28-13,W2,5-5,52.2,1.5%,100.0%
3,Milwaukee,36,28,.563,18.5,114.6,112.5,2.1,22-11,14-17,6-7,26-19,L3,6-4,43.9,0.0%,88.5%
4,Indiana,36,28,.563,18.5,116.4,115.4,1.0,20-10,16-18,8-5,21-20,W1,5-5,46.0,0.0%,98.0%
5,Detroit,37,29,.561,18.5,114.8,112.9,1.9,18-14,19-15,4-9,25-20,W2,7-3,42.8,0.0%,88.6%
6,Atlanta,32,34,.485,23.5,117.4,119.6,-2.2,17-16,15-18,8-4,24-18,W4,6-4,39.0,45.7%,73.4%
7,Orlando,30,36,.455,25.5,104.3,106.1,-1.8,18-16,12-20,8-3,24-20,L1,3-7,38.2,24.5%,60.9%
8,Miami,29,36,.446,26.0,109.9,110.6,-0.7,15-16,14-20,7-5,18-22,L5,3-7,38.5,29.8%,60.6%
9,Chicago,27,38,.415,28.0,116.6,120.3,-3.7,12-22,15-16,4-11,22-23,W3,5-5,31.7,0.0%,3.1%
10,Toronto,23,43,.348,32.5,110.8,115.7,-4.9,16-20,7-23,5-8,15-29,W2,6-4,28.2,0.0%,<1.0%
11,Brooklyn,22,43,.338,33.0,105.2,111.5,-6.3,10-21,12-22,3-8,12-28,L1,2-8,31.0,0.0%,2.4%
12,Philadelphia,22,43,.338,33.0,109.4,114.4,-5.0,12-21,10-22,3-11,14-27,L2,2-8,33.9,0.0%,23.6%
13,Charlotte,16,49,.246,39.0,105.4,113.0,-7.6,10-24,6-25,1-12,9-33,L1,2-8,24.1,0.0%,<1.0%
14,Washington,13,51,.203,41.5,108.3,120.6,-12.3,7-26,6-25,6-6,10-28,L2,4-6,15.6,0.0%,0.0%

Western Conference

In [149]:
#Find the tbody containing west conference teams, you can use select ('tbody')[0],means second tbody found
westConf = nbaTbls.select('tbody')[1]

In [150]:
#Team Names Western Conference
team = []

for teams in westConf.find_all('span', class_ = 'TeamName'):

  team.append(teams.get_text())

#team

In [151]:
#Data for Western Conference


data = []
for tr in westConf.find_all('tr'):
  row_data = []
  for i, td in enumerate(tr.find_all('td')):
    if i > 1:
      row_data.append(td.get_text().strip())
  data.append(row_data)

#data

In [152]:
#Teams Data Frame for Western Conference

team_df2 = pd.DataFrame(team, columns = ['Team'])
team_df2

             Team
0   Oklahoma City
1         Memphis
2          Denver
3     L.A. Lakers
4         Houston
5      Golden St.
6       Minnesota
7   L.A. Clippers
8      Sacramento
9          Dallas
10        Phoenix
11    San Antonio
12       Portland
13    New Orleans
14           Utah

In [153]:
#Data Frame of Western Coference

team_data2 = pd.DataFrame(data, columns = col_names)
team_data2

,W,L,PCT,GB,PPG,OPPG,Diff,Home,Road,Div,Conf,STRK,L10,W,Div,Post
0,54,12,.818,—,119.7,107.2,12.5,29-5,25-7,11-4,32-11,W1,8-2,66.1,100.0%,100.0%
1,42,24,.636,12.0,122.6,116.7,5.9,24-10,18-14,10-5,25-16,W4,5-5,52.0,78.1%,99.8%
2,42,24,.636,12.0,121.1,116.6,4.5,22-10,20-14,7-6,25-15,L1,5-5,52.8,0.0%,100.0%
3,40,23,.635,12.5,112.9,111.1,1.8,25-7,15-16,11-3,27-12,L2,8-2,46.1,38.6%,78.4%
4,41,25,.621,13.0,112.9,108.8,4.1,23-10,18-15,12-3,25-16,W4,6-4,48.7,21.5%,94.4%
5,37,28,.569,16.5,113.6,111.3,2.3,19-13,18-15,2-10,21-19,W5,9-1,44.6,11.8%,65.0%
6,38,29,.567,16.5,112.9,109.0,3.9,18-14,20-15,8-5,27-18,W6,7-3,45.8,0.0%,78.9%
7,36,30,.545,18.0,111.1,108.9,2.2,22-10,14-20,7-7,21-22,W1,5-5,46.8,47.9%,85.7%
8,33,31,.516,20.0,116.6,115.2,1.4,16-15,17-16,4-8,23-21,L2,5-5,41.7,1.7%,31.5%
9,33,34,.493,21.5,114.8,114.6,0.2,19-15,14-19,8-6,23-24,L1,2-8,43.8,0.0%,61.3%
10,30,36,.455,24.0,114.3,116.4,-2.1,18-13,12-23,8-4,20-24,L2,3-7,37.7,0.0%,3.5%
11,27,37,.422,26.0,113.8,116.1,-2.3,16-16,11-21,4-11,19-25,W1,3-7,35.9,0.0%,<1.0%
12,28,39,.418,26.5,110.6,114.6,-4.0,16-16,12-23,5-9,15-30,L5,4-6,32.4,0.0%,0.0%
13,18,48,.273,36.0,111.0,119.1,-8.1,12-21,6-27,3-12,12-32,W1,5-5,24.7,0.0%,0.0%
14,15,51,.227,39.0,112.5,119.8,-7.3,8-24,7-27,2-9,7-37,L7,1-9,24.3,0.0%,0.0%

In [154]:
#Combine both DataFrame (Western Conference)

df_final2 = pd.concat([team_df2, team_data2], axis = 1)
df_final2

,Team,W,L,PCT,GB,PPG,OPPG,Diff,Home,Road,Div,Conf,STRK,L10,W,Div,Post
0,Oklahoma City,54,12,.818,—,119.7,107.2,12.5,29-5,25-7,11-4,32-11,W1,8-2,66.1,100.0%,100.0%
1,Memphis,42,24,.636,12.0,122.6,116.7,5.9,24-10,18-14,10-5,25-16,W4,5-5,52.0,78.1%,99.8%
2,Denver,42,24,.636,12.0,121.1,116.6,4.5,22-10,20-14,7-6,25-15,L1,5-5,52.8,0.0%,100.0%
3,L.A. Lakers,40,23,.635,12.5,112.9,111.1,1.8,25-7,15-16,11-3,27-12,L2,8-2,46.1,38.6%,78.4%
4,Houston,41,25,.621,13.0,112.9,108.8,4.1,23-10,18-15,12-3,25-16,W4,6-4,48.7,21.5%,94.4%
5,Golden St.,37,28,.569,16.5,113.6,111.3,2.3,19-13,18-15,2-10,21-19,W5,9-1,44.6,11.8%,65.0%
6,Minnesota,38,29,.567,16.5,112.9,109.0,3.9,18-14,20-15,8-5,27-18,W6,7-3,45.8,0.0%,78.9%
7,L.A. Clippers,36,30,.545,18.0,111.1,108.9,2.2,22-10,14-20,7-7,21-22,W1,5-5,46.8,47.9%,85.7%
8,Sacramento,33,31,.516,20.0,116.6,115.2,1.4,16-15,17-16,4-8,23-21,L2,5-5,41.7,1.7%,31.5%
9,Dallas,33,34,.493,21.5,114.8,114.6,0.2,19-15,14-19,8-6,23-24,L1,2-8,43.8,0.0%,61.3%
10,Phoenix,30,36,.455,24.0,114.3,116.4,-2.1,18-13,12-23,8-4,20-24,L2,3-7,37.7,0.0%,3.5%
11,San Antonio,27,37,.422,26.0,113.8,116.1,-2.3,16-16,11-21,4-11,19-25,W1,3-7,35.9,0.0%,<1.0%
12,Portland,28,39,.418,26.5,110.6,114.6,-4.0,16-16,12-23,5-9,15-30,L5,4-6,32.4,0.0%,0.0%
13,New Orleans,18,48,.273,36.0,111.0,119.1,-8.1,12-21,6-27,3-12,12-32,W1,5-5,24.7,0.0%,0.0%
14,Utah,15,51,.227,39.0,112.5,119.8,-7.3,8-24,7-27,2-9,7-37,L7,1-9,24.3,0.0%,0.0%

Combine Eastern Conference and Western Conference Data

In [155]:
#Combine both DataFrame (Eastern Conference)

df_combine = pd.concat([df_final, df_final2], axis = 0)
df_combine

,Team,W,L,PCT,GB,PPG,OPPG,Diff,Home,Road,Div,Conf,STRK,L10,W,Div,Post
0,Cleveland,55,10,.846,—,122.7,111.4,11.3,30-4,25-6,11-1,38-7,W15,10-0,62.9,100.0%,100.0%
1,Boston,47,19,.712,8.5,116.8,108.3,8.5,23-12,24-7,11-2,32-11,L1,7-3,59.7,98.5%,100.0%
2,New York,42,23,.646,13.0,117.1,112.7,4.4,21-11,21-12,10-3,28-13,W2,5-5,52.2,1.5%,100.0%
3,Milwaukee,36,28,.563,18.5,114.6,112.5,2.1,22-11,14-17,6-7,26-19,L3,6-4,43.9,0.0%,88.5%
4,Indiana,36,28,.563,18.5,116.4,115.4,1.0,20-10,16-18,8-5,21-20,W1,5-5,46.0,0.0%,98.0%
5,Detroit,37,29,.561,18.5,114.8,112.9,1.9,18-14,19-15,4-9,25-20,W2,7-3,42.8,0.0%,88.6%
6,Atlanta,32,34,.485,23.5,117.4,119.6,-2.2,17-16,15-18,8-4,24-18,W4,6-4,39.0,45.7%,73.4%
7,Orlando,30,36,.455,25.5,104.3,106.1,-1.8,18-16,12-20,8-3,24-20,L1,3-7,38.2,24.5%,60.9%
8,Miami,29,36,.446,26.0,109.9,110.6,-0.7,15-16,14-20,7-5,18-22,L5,3-7,38.5,29.8%,60.6%
9,Chicago,27,38,.415,28.0,116.6,120.3,-3.7,12-22,15-16,4-11,22-23,W3,5-5,31.7,0.0%,3.1%
10,Toronto,23,43,.348,32.5,110.8,115.7,-4.9,16-20,7-23,5-8,15-29,W2,6-4,28.2,0.0%,<1.0%
11,Brooklyn,22,43,.338,33.0,105.2,111.5,-6.3,10-21,12-22,3-8,12-28,L1,2-8,31.0,0.0%,2.4%
12,Philadelphia,22,43,.338,33.0,109.4,114.4,-5.0,12-21,10-22,3-11,14-27,L2,2-8,33.9,0.0%,23.6%
13,Charlotte,16,49,.246,39.0,105.4,113.0,-7.6,10-24,6-25,1-12,9-33,L1,2-8,24.1,0.0%,<1.0%
14,Washington,13,51,.203,41.5,108.3,120.6,-12.3,7-26,6-25,6-6,10-28,L2,4-6,15.6,0.0%,0.0%
0,Oklahoma City,54,12,.818,—,119.7,107.2,12.5,29-5,25-7,11-4,32-11,W1,8-2,66.1,100.0%,100.0%
1,Memphis,42,24,.636,12.0,122.6,116.7,5.9,24-10,18-14,10-5,25-16,W4,5-5,52.0,78.1%,99.8%
2,Denver,42,24,.636,12.0,121.1,116.6,4.5,22-10,20-14,7-6,25-15,L1,5-5,52.8,0.0%,100.0%
3,L.A. Lakers,40,23,.635,12.5,112.9,111.1,1.8,25-7,15-16,11-3,27-12,L2,8-2,46.1,38.6%,78.4%
4,Houston,41,25,.621,13.0,112.9,108.8,4.1,23-10,18-15,12-3,25-16,W4,6-4,48.7,21.5%,94.4%
5,Golden St.,37,28,.569,16.5,113.6,111.3,2.3,19-13,18-15,2-10,21-19,W5,9-1,44.6,11.8%,65.0%
6,Minnesota,38,29,.567,16.5,112.9,109.0,3.9,18-14,20-15,8-5,27-18,W6,7-3,45.8,0.0%,78.9%
7,L.A. Clippers,36,30,.545,18.0,111.1,108.9,2.2,22-10,14-20,7-7,21-22,W1,5-5,46.8,47.9%,85.7%
8,Sacramento,33,31,.516,20.0,116.6,115.2,1.4,16-15,17-16,4-8,23-21,L2,5-5,41.7,1.7%,31.5%
9,Dallas,33,34,.493,21.5,114.8,114.6,0.2,19-15,14-19,8-6,23-24,L1,2-8,43.8,0.0%,61.3%
10,Phoenix,30,36,.455,24.0,114.3,116.4,-2.1,18-13,12-23,8-4,20-24,L2,3-7,37.7,0.0%,3.5%
11,San Antonio,27,37,.422,26.0,113.8,116.1,-2.3,16-16,11-21,4-11,19-25,W1,3-7,35.9,0.0%,<1.0%
12,Portland,28,39,.418,26.5,110.6,114.6,-4.0,16-16,12-23,5-9,15-30,L5,4-6,32.4,0.0%,0.0%
13,New Orleans,18,48,.273,36.0,111.0,119.1,-8.1,12-21,6-27,3-12,12-32,W1,5-5,24.7,0.0%,0.0%
14,Utah,15,51,.227,39.0,112.5,119.8,-7.3,8-24,7-27,2-9,7-37,L7,1-9,24.3,0.0%,0.0%

In [156]:
#Sort by PCT in Descending Order
df_combine.sort_values(by = 'PCT', ascending = False)
df_combine

,Team,W,L,PCT,GB,PPG,OPPG,Diff,Home,Road,Div,Conf,STRK,L10,W,Div,Post
0,Cleveland,55,10,.846,—,122.7,111.4,11.3,30-4,25-6,11-1,38-7,W15,10-0,62.9,100.0%,100.0%
1,Boston,47,19,.712,8.5,116.8,108.3,8.5,23-12,24-7,11-2,32-11,L1,7-3,59.7,98.5%,100.0%
2,New York,42,23,.646,13.0,117.1,112.7,4.4,21-11,21-12,10-3,28-13,W2,5-5,52.2,1.5%,100.0%
3,Milwaukee,36,28,.563,18.5,114.6,112.5,2.1,22-11,14-17,6-7,26-19,L3,6-4,43.9,0.0%,88.5%
4,Indiana,36,28,.563,18.5,116.4,115.4,1.0,20-10,16-18,8-5,21-20,W1,5-5,46.0,0.0%,98.0%
5,Detroit,37,29,.561,18.5,114.8,112.9,1.9,18-14,19-15,4-9,25-20,W2,7-3,42.8,0.0%,88.6%
6,Atlanta,32,34,.485,23.5,117.4,119.6,-2.2,17-16,15-18,8-4,24-18,W4,6-4,39.0,45.7%,73.4%
7,Orlando,30,36,.455,25.5,104.3,106.1,-1.8,18-16,12-20,8-3,24-20,L1,3-7,38.2,24.5%,60.9%
8,Miami,29,36,.446,26.0,109.9,110.6,-0.7,15-16,14-20,7-5,18-22,L5,3-7,38.5,29.8%,60.6%
9,Chicago,27,38,.415,28.0,116.6,120.3,-3.7,12-22,15-16,4-11,22-23,W3,5-5,31.7,0.0%,3.1%
10,Toronto,23,43,.348,32.5,110.8,115.7,-4.9,16-20,7-23,5-8,15-29,W2,6-4,28.2,0.0%,<1.0%
11,Brooklyn,22,43,.338,33.0,105.2,111.5,-6.3,10-21,12-22,3-8,12-28,L1,2-8,31.0,0.0%,2.4%
12,Philadelphia,22,43,.338,33.0,109.4,114.4,-5.0,12-21,10-22,3-11,14-27,L2,2-8,33.9,0.0%,23.6%
13,Charlotte,16,49,.246,39.0,105.4,113.0,-7.6,10-24,6-25,1-12,9-33,L1,2-8,24.1,0.0%,<1.0%
14,Washington,13,51,.203,41.5,108.3,120.6,-12.3,7-26,6-25,6-6,10-28,L2,4-6,15.6,0.0%,0.0%
0,Oklahoma City,54,12,.818,—,119.7,107.2,12.5,29-5,25-7,11-4,32-11,W1,8-2,66.1,100.0%,100.0%
1,Memphis,42,24,.636,12.0,122.6,116.7,5.9,24-10,18-14,10-5,25-16,W4,5-5,52.0,78.1%,99.8%
2,Denver,42,24,.636,12.0,121.1,116.6,4.5,22-10,20-14,7-6,25-15,L1,5-5,52.8,0.0%,100.0%
3,L.A. Lakers,40,23,.635,12.5,112.9,111.1,1.8,25-7,15-16,11-3,27-12,L2,8-2,46.1,38.6%,78.4%
4,Houston,41,25,.621,13.0,112.9,108.8,4.1,23-10,18-15,12-3,25-16,W4,6-4,48.7,21.5%,94.4%
5,Golden St.,37,28,.569,16.5,113.6,111.3,2.3,19-13,18-15,2-10,21-19,W5,9-1,44.6,11.8%,65.0%
6,Minnesota,38,29,.567,16.5,112.9,109.0,3.9,18-14,20-15,8-5,27-18,W6,7-3,45.8,0.0%,78.9%
7,L.A. Clippers,36,30,.545,18.0,111.1,108.9,2.2,22-10,14-20,7-7,21-22,W1,5-5,46.8,47.9%,85.7%
8,Sacramento,33,31,.516,20.0,116.6,115.2,1.4,16-15,17-16,4-8,23-21,L2,5-5,41.7,1.7%,31.5%
9,Dallas,33,34,.493,21.5,114.8,114.6,0.2,19-15,14-19,8-6,23-24,L1,2-8,43.8,0.0%,61.3%
10,Phoenix,30,36,.455,24.0,114.3,116.4,-2.1,18-13,12-23,8-4,20-24,L2,3-7,37.7,0.0%,3.5%
11,San Antonio,27,37,.422,26.0,113.8,116.1,-2.3,16-16,11-21,4-11,19-25,W1,3-7,35.9,0.0%,<1.0%
12,Portland,28,39,.418,26.5,110.6,114.6,-4.0,16-16,12-23,5-9,15-30,L5,4-6,32.4,0.0%,0.0%
13,New Orleans,18,48,.273,36.0,111.0,119.1,-8.1,12-21,6-27,3-12,12-32,W1,5-5,24.7,0.0%,0.0%
14,Utah,15,51,.227,39.0,112.5,119.8,-7.3,8-24,7-27,2-9,7-37,L7,1-9,24.3,0.0%,0.0%

In [157]:
#Reset Index
df_combine.reset_index(drop = True, inplace = True)
df_combine

,Team,W,L,PCT,GB,PPG,OPPG,Diff,Home,Road,Div,Conf,STRK,L10,W,Div,Post
0,Cleveland,55,10,.846,—,122.7,111.4,11.3,30-4,25-6,11-1,38-7,W15,10-0,62.9,100.0%,100.0%
1,Boston,47,19,.712,8.5,116.8,108.3,8.5,23-12,24-7,11-2,32-11,L1,7-3,59.7,98.5%,100.0%
2,New York,42,23,.646,13.0,117.1,112.7,4.4,21-11,21-12,10-3,28-13,W2,5-5,52.2,1.5%,100.0%
3,Milwaukee,36,28,.563,18.5,114.6,112.5,2.1,22-11,14-17,6-7,26-19,L3,6-4,43.9,0.0%,88.5%
4,Indiana,36,28,.563,18.5,116.4,115.4,1.0,20-10,16-18,8-5,21-20,W1,5-5,46.0,0.0%,98.0%
5,Detroit,37,29,.561,18.5,114.8,112.9,1.9,18-14,19-15,4-9,25-20,W2,7-3,42.8,0.0%,88.6%
6,Atlanta,32,34,.485,23.5,117.4,119.6,-2.2,17-16,15-18,8-4,24-18,W4,6-4,39.0,45.7%,73.4%
7,Orlando,30,36,.455,25.5,104.3,106.1,-1.8,18-16,12-20,8-3,24-20,L1,3-7,38.2,24.5%,60.9%
8,Miami,29,36,.446,26.0,109.9,110.6,-0.7,15-16,14-20,7-5,18-22,L5,3-7,38.5,29.8%,60.6%
9,Chicago,27,38,.415,28.0,116.6,120.3,-3.7,12-22,15-16,4-11,22-23,W3,5-5,31.7,0.0%,3.1%
10,Toronto,23,43,.348,32.5,110.8,115.7,-4.9,16-20,7-23,5-8,15-29,W2,6-4,28.2,0.0%,<1.0%
11,Brooklyn,22,43,.338,33.0,105.2,111.5,-6.3,10-21,12-22,3-8,12-28,L1,2-8,31.0,0.0%,2.4%
12,Philadelphia,22,43,.338,33.0,109.4,114.4,-5.0,12-21,10-22,3-11,14-27,L2,2-8,33.9,0.0%,23.6%
13,Charlotte,16,49,.246,39.0,105.4,113.0,-7.6,10-24,6-25,1-12,9-33,L1,2-8,24.1,0.0%,<1.0%
14,Washington,13,51,.203,41.5,108.3,120.6,-12.3,7-26,6-25,6-6,10-28,L2,4-6,15.6,0.0%,0.0%
15,Oklahoma City,54,12,.818,—,119.7,107.2,12.5,29-5,25-7,11-4,32-11,W1,8-2,66.1,100.0%,100.0%
16,Memphis,42,24,.636,12.0,122.6,116.7,5.9,24-10,18-14,10-5,25-16,W4,5-5,52.0,78.1%,99.8%
17,Denver,42,24,.636,12.0,121.1,116.6,4.5,22-10,20-14,7-6,25-15,L1,5-5,52.8,0.0%,100.0%
18,L.A. Lakers,40,23,.635,12.5,112.9,111.1,1.8,25-7,15-16,11-3,27-12,L2,8-2,46.1,38.6%,78.4%
19,Houston,41,25,.621,13.0,112.9,108.8,4.1,23-10,18-15,12-3,25-16,W4,6-4,48.7,21.5%,94.4%
20,Golden St.,37,28,.569,16.5,113.6,111.3,2.3,19-13,18-15,2-10,21-19,W5,9-1,44.6,11.8%,65.0%
21,Minnesota,38,29,.567,16.5,112.9,109.0,3.9,18-14,20-15,8-5,27-18,W6,7-3,45.8,0.0%,78.9%
22,L.A. Clippers,36,30,.545,18.0,111.1,108.9,2.2,22-10,14-20,7-7,21-22,W1,5-5,46.8,47.9%,85.7%
23,Sacramento,33,31,.516,20.0,116.6,115.2,1.4,16-15,17-16,4-8,23-21,L2,5-5,41.7,1.7%,31.5%
24,Dallas,33,34,.493,21.5,114.8,114.6,0.2,19-15,14-19,8-6,23-24,L1,2-8,43.8,0.0%,61.3%
25,Phoenix,30,36,.455,24.0,114.3,116.4,-2.1,18-13,12-23,8-4,20-24,L2,3-7,37.7,0.0%,3.5%
26,San Antonio,27,37,.422,26.0,113.8,116.1,-2.3,16-16,11-21,4-11,19-25,W1,3-7,35.9,0.0%,<1.0%
27,Portland,28,39,.418,26.5,110.6,114.6,-4.0,16-16,12-23,5-9,15-30,L5,4-6,32.4,0.0%,0.0%
28,New Orleans,18,48,.273,36.0,111.0,119.1,-8.1,12-21,6-27,3-12,12-32,W1,5-5,24.7,0.0%,0.0%
29,Utah,15,51,.227,39.0,112.5,119.8,-7.3,8-24,7-27,2-9,7-37,L7,1-9,24.3,0.0%,0.0%